<a href="https://colab.research.google.com/github/Hadassah22/MLproject/blob/main/MLmovierecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MOVIE RECOMMENDATION SYSTEM

Importing the libraries

In [1]:
import numpy as np
import pandas as pd

Uploading the dataset

In [2]:
df=pd.read_csv("IMDB-Movie-Data.csv")

In [3]:
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Number of rowns and columns in the dataframe



In [4]:
df.shape

(1000, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                1000 non-null   int64  
 1   Title               1000 non-null   object 
 2   Genre               1000 non-null   object 
 3   Description         1000 non-null   object 
 4   Director            1000 non-null   object 
 5   Actors              1000 non-null   object 
 6   Year                1000 non-null   int64  
 7   Runtime (Minutes)   1000 non-null   int64  
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64  
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB


Selecting important features

In [6]:
selected_features=['Genre','Description','Actors','Director']

Checking for null values

In [7]:
df.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                1000 non-null   int64  
 1   Title               1000 non-null   object 
 2   Genre               1000 non-null   object 
 3   Description         1000 non-null   object 
 4   Director            1000 non-null   object 
 5   Actors              1000 non-null   object 
 6   Year                1000 non-null   int64  
 7   Runtime (Minutes)   1000 non-null   int64  
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64  
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB


Replacing the null values with null string

In [9]:

for feature in selected_features:
  df[feature] = df[feature].fillna('') 

In [10]:
revenue_mean=np.mean(df['Revenue (Millions)'],axis=None)
df['Revenue (Millions)']=df['Revenue (Millions)'].fillna(revenue_mean)
df['Revenue (Millions)']=df['Revenue (Millions)'].astype(int)

In [11]:
revenue_mean=np.mean(df['Metascore'],axis=None)
df['Metascore']=df['Metascore'].fillna(revenue_mean)
df['Metascore']=df['Metascore'].astype(int)

In [12]:
df.isnull().sum()

Rank                  0
Title                 0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
dtype: int64

Combining the features

In [13]:
combined_features = df['Genre']+' '+df['Description']+' '+df['Director']+' '+df['Actors']

In [14]:
print(combined_features)

0      Action,Adventure,Sci-Fi A group of intergalact...
1      Adventure,Mystery,Sci-Fi Following clues to th...
2      Horror,Thriller Three girls are kidnapped by a...
3      Animation,Comedy,Family In a city of humanoid ...
4      Action,Adventure,Fantasy A secret government a...
                             ...                        
995    Crime,Drama,Mystery A tight-knit team of risin...
996    Horror Three American college students studyin...
997    Drama,Music,Romance Romantic sparks occur betw...
998    Adventure,Comedy A pair of friends embark on a...
999    Comedy,Family,Fantasy A stuffy businessman fin...
Length: 1000, dtype: object


Converting the text data to feature vectors

In [15]:
vectorizer = TfidfVectorizer()

In [16]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [17]:
print(feature_vectors)

  (0, 6866)	0.2208390477858074
  (0, 8820)	0.21589359852035722
  (0, 1791)	0.18385767904288147
  (0, 1087)	0.19791240156183035
  (0, 2242)	0.21589359852035722
  (0, 8417)	0.21589359852035722
  (0, 6192)	0.21589359852035722
  (0, 1513)	0.1458643387421238
  (0, 3497)	0.24156489683885848
  (0, 4178)	0.13015531275725872
  (0, 8265)	0.2208390477858074
  (0, 7885)	0.04918789804567106
  (0, 1775)	0.20762928635939698
  (0, 7744)	0.20762928635939698
  (0, 3151)	0.10758206477554348
  (0, 8516)	0.20409939238136726
  (0, 2853)	0.26723619515735975
  (0, 7537)	0.17520555334070667
  (0, 8000)	0.1645510018833547
  (0, 8733)	0.18015100260615685
  (0, 7992)	0.10836950062008444
  (0, 3055)	0.1708433579369093
  (0, 495)	0.12880840596915433
  (0, 1897)	0.23330058467789824
  (0, 4057)	0.23330058467789824
  :	:
  (998, 206)	0.08815189273478231
  (999, 3727)	0.2702249772069396
  (999, 1483)	0.2702249772069396
  (999, 7593)	0.2702249772069396
  (999, 354)	0.2550402823496917
  (999, 7386)	0.23590982927978008
  

Cosine Similarity

In [18]:
similarity = cosine_similarity(feature_vectors)

In [19]:
print(similarity)

[[1.         0.06046774 0.04060199 ... 0.02133447 0.02899224 0.00933189]
 [0.06046774 1.         0.04458906 ... 0.0069634  0.02655796 0.02538796]
 [0.04060199 0.04458906 1.         ... 0.00632286 0.01673092 0.00491672]
 ...
 [0.02133447 0.0069634  0.00632286 ... 1.         0.03305475 0.00765816]
 [0.02899224 0.02655796 0.01673092 ... 0.03305475 1.         0.01330482]
 [0.00933189 0.02538796 0.00491672 ... 0.00765816 0.01330482 1.        ]]


In [20]:
print(similarity.shape)

(1000, 1000)


Getting a movie name from the user 

In [21]:
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : suicide squad


Creating a list withh all the movie names given in the dataset

In [22]:
titles = df['Title'].tolist()

Finding a close match for the movie entered by the user 

In [23]:
find_match = difflib.get_close_matches(movie_name, titles)

In [24]:
close_match =find_match[0]

Finding the index of the movie with title

In [25]:
index_of_the_movie = df[df.Title ==close_match]['Rank'].values[0]

Getting the index of the movie along with similar codes 

In [26]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))

len(similarity_score)

[(0, 0.03305235673874677), (1, 0.017437404511717696), (2, 0.010573173639058811), (3, 0.012049305401352123), (4, 0.03914023466418492), (5, 1.0000000000000002), (6, 0.01289247432467972), (7, 0.016491878000470875), (8, 0.07087993150836976), (9, 0.014931693544588651), (10, 0.03983522936418262), (11, 0.03502780509170072), (12, 0.031567294197270716), (13, 0.016289691218275552), (14, 0.015306491583824543), (15, 0.019911331281493735), (16, 0.024653714686539374), (17, 0.07738130678203087), (18, 0.018076805358836493), (19, 0.017719189034849016), (20, 0.024881960404865094), (21, 0.012635612650023161), (22, 0.01736727475236605), (23, 0.014528888679912803), (24, 0.013223252336188979), (25, 0.013748130556227176), (26, 0.0173708793631452), (27, 0.010655256113433091), (28, 0.013062299799360735), (29, 0.042404913299141936), (30, 0.009950087364910078), (31, 0.0), (32, 0.030412002960165434), (33, 0.023877468246594348), (34, 0.05145494336555006), (35, 0.01835643503176569), (36, 0.022469919684358994), (37,

1000

Sorting the movies based on the similarity score





In [27]:
sorted_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_movies)
len(sorted_movies)

[(5, 1.0000000000000002), (528, 0.11787567980507226), (427, 0.1163953953607326), (389, 0.10631518888807097), (416, 0.1004733874143746), (53, 0.09854840783170914), (720, 0.0936735253695998), (585, 0.08831111268572206), (609, 0.08821881143944699), (685, 0.08563586840554416), (854, 0.08518613753973235), (156, 0.08216995173696891), (176, 0.08126388662213918), (204, 0.0791212519388881), (95, 0.07809237523626796), (17, 0.07738130678203087), (526, 0.07435835500524701), (938, 0.07361150961870715), (907, 0.07136528642599954), (909, 0.07122352933189102), (8, 0.07087993150836976), (622, 0.07039627664456667), (91, 0.07000970025605482), (743, 0.06992571660175849), (440, 0.06879893932990741), (833, 0.06784702156269252), (99, 0.06776156163496985), (706, 0.06580093275690224), (827, 0.06498266509591522), (177, 0.06482866295287638), (408, 0.06212478364013497), (313, 0.060527335995949845), (430, 0.06040440123960284), (102, 0.060066097328938035), (418, 0.059085727174235776), (578, 0.05872496006537374), (5

1000

Printing the recomended movies 

In [28]:
print('Movies suggested for you : \n')

i = 999
for movie in sorted_movies:
  index = movie[0]
  title_from_index = df[df.index==index]['Title'].values[0]
  if (i>990):
    print(10-i%90, '.',title_from_index)
    i-=1

Movies suggested for you : 

1 . The Great Wall
2 . Godzilla
3 . The Bourne Ultimatum
4 . John Carter
5 . The Headhunter's Calling
6 . John Wick
7 . Nymphomaniac: Vol. II
8 . Ghost Rider
9 . Hellboy II: The Golden Army
